# Generated by Django 6.0 on 2026-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_subscriber_blog_blogsection_comment_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchgroup',
            name='can_manage_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='churchgroup',
            name='can_manage_finances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='churchgroup',
            name='can_manage_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
