# Generated by Django 6.0 on 2026-01-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_churchgroup_can_manage_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchgroup',
            name='can_manage_blog',
        ),
        migrations.RemoveField(
            model_name='churchgroup',
            name='can_manage_finances',
        ),
        migrations.RemoveField(
            model_name='churchgroup',
            name='can_manage_gallery',
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='can_manage_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='can_manage_finances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='can_manage_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
