# Generated by Django 6.0 on 2026-01-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_churchgroup_can_manage_blog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembership',
            old_name='can_manage_finances',
            new_name='can_manage_videos',
        ),
    ]
