# Generated by Django 6.0 on 2026-01-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_can_manage_finances_groupmembership_can_manage_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='blog_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogsection',
            name='image',
        ),
        migrations.AddField(
            model_name='blogsection',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
